<?php
// Introduction to PHP

// PHP(Recursing acronym for Hypertext Preprocessor) is a server-side scipt programmming language primarily used for web Development
// PHP code is executed on the server and the result is sent to the client's browser

// PHP files have .php extension and can contain a mixture oh HTML and Php code

// Basic syntax

// PHP code is enclosed within <?php
// statements are terminated with a semi-colon(;)
// PHP i s alosely typed langugae but supports type declarations with data types
// Comments can be single // or multiline/* */ 
// this is a single line comment
echo "Hello,Everyone";  

/**
 * this is a multiline comment
 */

//  Variables
// in php variables start with $ followed by the variable name
// variables are dynamically types based on their value

// Common Data Types: integers,strings,floats,boolean, null,objects,arrays

// Variable naming follows camelCase convention

?>